src/main/java/com/teamsupercat/roupangbackend/config/SwaggerRedirector.java

Swagger 접속경로 추가(경로라우팅)
주소: http://localhost:8080/TeamSuperCat

Swagger 접속경로 추가

---

src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/AllProductsResponse.java
src/main/java/com/teamsupercat/roupangbackend/repository/ProductRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

판매자가 자신이 파는 판매 물품 전체 조회할 수 있는 기능 추가했습니다.

Feat: [쇼핑몰] 판매자의 판매 물품 전체 조회 기능 추가

---

src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionDetailRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionTypeRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductResponse.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionDetail.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionType.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

Feat: [쇼핑몰] 물품 상세 조회에 옵션 조회 기능 추가
물품을 상세 조회 시, 옵션도 출력되서 나온다.

Feat: [쇼핑몰] 물품 상세 조회에 옵션 조회 기능 추가

---

src/main/java/com/teamsupercat/roupangbackend/common/CustomExceptionHandler.java
src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/common/dynamicMessageException/CustomMessageException.java
src/main/java/com/teamsupercat/roupangbackend/controller/CartOrderController.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/request/PurchaseItemRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/response/CartAllResponse.java
src/main/java/com/teamsupercat/roupangbackend/entity/Payment.java
src/main/java/com/teamsupercat/roupangbackend/entity/SingleOrder.java
src/main/java/com/teamsupercat/roupangbackend/repository/CartRepository.java
src/main/java/com/teamsupercat/roupangbackend/repository/GroupedOrderRepository.java
src/main/java/com/teamsupercat/roupangbackend/repository/PaymentRepository.java
src/main/java/com/teamsupercat/roupangbackend/repository/SingleOrderRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/CartOrderService.java
src/main/java/com/teamsupercat/roupangbackend/service/CartService.java

1. 결제하면 상품재고 감소 기능추가
2. 결제하면 유저 포인트 차감(임시) 기능추가
3. 결제 후 카트 비우기 기능추가
4.
장바구니에 상품재고 나오게 추가
1. 기존 장바구니 상품을 개별주문테이블에 이동시킨 후
2. 개별주문의 inx값을 가지고
묶음주문 번호를 만들었습니다.
3. 묶음 주문번호를 통해 결제를 하였고 유저의 포인트를 차감시켰습니다
4. 결제가 완료되면
장바구니를 모두 비웁니다.
5. 구매한 수량만큼 판매상품의 재고를 차감시킵니다.

feat: 장바구니 상품 결제기능

---

src/main/java/com/teamsupercat/roupangbackend/dto/myPage/MyPageDto.java

request -> email
response -> memberIdx
추가

refactor : MyPageDto 필드 누락

---

src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionDetail.java
src/main/java/com/teamsupercat/roupangbackend/repository/OptionDetailRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/OptionService.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

feat: 옵션으로 물품 조회 API 생성

---

src/main/java/com/teamsupercat/roupangbackend/controller/CartController.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/request/RemoveCartRequest.java
src/main/java/com/teamsupercat/roupangbackend/repository/CartRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/CartService.java

1. 장바구니에 담겨있는 상품 중 삭제하고 싶은 항목의 상품번호를 요청보내면 단일상품을 삭제하는 기능

feat(장바구니): 장바구니 단일삭제 API 구현

---

src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionDetailRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionTypeRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionType.java
src/main/java/com/teamsupercat/roupangbackend/entity/Product.java
src/main/java/com/teamsupercat/roupangbackend/repository/ProductRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

feat: [쇼핑몰] 로그인된 유저 idx로 사용 가능하게 함, 판매자 물품 내역 조회(판매순) 추가 및 리펙토링 진행
기존 임시 integer Idx를 로그인 한 유저의 idx를 넣어서 되게끔 기능 수정, 판매자 물품 내역 조회에서 판매순 추가 및 리펙토링 진행

feat: [쇼핑몰] 로그인된 유저 idx로 사용 가능하게 함, 판매자 물품 내역 조회(판매순) 추가 및 리펙토링 진행

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/CartController.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/request/CartChangeRequest.java
src/main/java/com/teamsupercat/roupangbackend/repository/CartRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/CartService.java

장바구니Controller와 Service단 해석하기 쉽게 리팩토링 했습니다.

refactor(장바구니): 장바구니 Controller,Service리팩토링

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionDetailRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionTypeRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionType.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

feat: [쇼핑몰] 판매자의 판매 물품 등록시 옵션 기능 수정해서 적용.
판매자 물품 등록시 옵션 기능 수정함.

feat: [쇼핑몰] 판매자의 판매 물품 등록시 옵션 기능 수정해서 적용.

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionDetailRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionTypeRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/entity/Product.java
src/main/java/com/teamsupercat/roupangbackend/entity/Seller.java
src/main/java/com/teamsupercat/roupangbackend/repository/OptionDetailRepository.java
src/main/java/com/teamsupercat/roupangbackend/repository/OptionTypeRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

feat: [쇼핑몰] 판매자 물품 등록 수정, 판메자의 판매물품 수정 기능 구현
1. 판매자 물품 등록: 옵션 등록을 메소드로 따로 빼줌
2. 판매자의 판매 물품 수정 기능 추가

feat: [쇼핑몰] 판매자 물품 등록 수정, 판메자의 판매물품 수정 기능 구현

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/CartController.java
src/main/java/com/teamsupercat/roupangbackend/security/JwtTokenProvider.java
src/main/java/com/teamsupercat/roupangbackend/service/CartOrderService.java
src/main/java/com/teamsupercat/roupangbackend/service/CartService.java
src/main/java/com/teamsupercat/roupangbackend/service/MemberService.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java
src/main/java/com/teamsupercat/roupangbackend/service/RefreshTokenService.java
src/main/java/com/teamsupercat/roupangbackend/service/ViewHistoryService.java

- 코드 리팩토링을 통해서 에러 코드의 명확성과 일관성을 향상

refactor : ErrorCode 수정

---

src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionRegisterRequest1.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/entity/OptionType.java
src/main/java/com/teamsupercat/roupangbackend/service/OptionService.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java

feat: [쇼핑몰] 판매자 물품 등록 (옵션 기능) 리펙토링

feat: [쇼핑몰] 판매자 물품 등록 (옵션 기능) 리펙토링

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/ProductController.java
src/main/java/com/teamsupercat/roupangbackend/controller/SellerController.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java
src/main/java/com/teamsupercat/roupangbackend/service/SellerService.java

feat: [쇼핑몰] 판매자 관련 api, SellerController, SellerService 쪽으로 옮김

feat: [쇼핑몰] 판매자 관련 api, SellerController, SellerService 쪽으로 옮김

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java

feat: [쇼핑몰] 에러 코드 빠진거 올림

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/CartController.java
src/main/java/com/teamsupercat/roupangbackend/controller/CartOrderController.java
src/main/java/com/teamsupercat/roupangbackend/controller/ViewHistoryController.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/request/CartChangeRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/cart/response/CartAllResponse.java
src/main/java/com/teamsupercat/roupangbackend/dto/order/request/PurchaseItemRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/order/response/PurchaseItemResponse.java
src/main/java/com/teamsupercat/roupangbackend/entity/Cart.java
src/main/java/com/teamsupercat/roupangbackend/service/CartOrderService.java
src/main/java/com/teamsupercat/roupangbackend/service/CartService.java

기존 상품의 번호와 상품의 갯수만 받았지만
상품의 옵션도 추가로 받을 수 있게 추가하였습니다.

feat(장바구니): 장바구니 옵션기능 추가

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/controller/SellerController.java
src/main/java/com/teamsupercat/roupangbackend/dto/option/request/OptionWithProductRegisterRequest.java
src/main/java/com/teamsupercat/roupangbackend/dto/product/ProductCreateRequest.java
src/main/java/com/teamsupercat/roupangbackend/entity/Seller.java
src/main/java/com/teamsupercat/roupangbackend/repository/ProductRepository.java
src/main/java/com/teamsupercat/roupangbackend/service/OptionService.java
src/main/java/com/teamsupercat/roupangbackend/service/ProductService.java
src/main/java/com/teamsupercat/roupangbackend/service/SellerService.java

feat: [쇼핑몰] 판매자의 판매 물품 리스트 조회에서 정렬 쿼리 수정, 페이징 디폴트 사이즈 삽입

feat: [쇼핑몰] 판매자의 판매 물품 리스트 조회에서 정렬 쿼리 수정, 페이징 디폴트 사이즈 삽입

---

src/main/java/com/teamsupercat/roupangbackend/common/ErrorCode.java
src/main/java/com/teamsupercat/roupangbackend/service/SellerService.java

feat: [쇼핑몰] 판매자 등록에서 예외 처리 추가.

feat: [쇼핑몰] 판매자 등록에서 예외 처리 추가.

---

src/main/java/com/teamsupercat/roupangbackend/service/SellerService.java

feat: [쇼핑몰] 판매자 리스트 빠진 예외 추가

---

src/main/java/com/teamsupercat/roupangbackend/entity/DeliveryAddress.java
src/main/java/com/teamsupercat/roupangbackend/entity/Payment.java

DeliveryAddress Entity 추가 및 연관관계 재설정

feat/DeliveryAddress Entity 추가

---

src/main/java/com/teamsupercat/roupangbackend/controller/MyPageController.java
src/main/java/com/teamsupercat/roupangbackend/dto/MyPageDto.java
src/main/java/com/teamsupercat/roupangbackend/service/MyPageService.java

기존 작업도중 충돌방지를 위하여 mypage 패키지 별도 생성 하였으나 위치 변경

docs : 패키지 위치 변경

---

src/main/java/com/teamsupercat/roupangbackend/service/SellerService.java

feat: [쇼핑몰] 판매자 리스트에 판매 물품이 없을 경우 204 예외 대신 빈 content로 보내주는 것으로 대체

feat: [쇼핑몰] 판매자 리스트에 판매 물품이 없을 경우 204 예외 대신 빈 content로 보내주는 것으로 대체

---

src/main/java/com/teamsupercat/roupangbackend/entity/PointTransaction.java

feat : 포인트 충전기능 추가

---

src/main/java/com/teamsupercat/roupangbackend/controller/PointTransactionController.java
src/main/java/com/teamsupercat/roupangbackend/service/PointTransactionService.java

refactor : 안쓰는 import 및 미구현 주석코드 삭제
